INSERT INTO blogful_articles (title, date_published, content) VALUES 
    ('title oafsdne', now() - '21 days'::INTERVAL, 'ABCDES'),
    ('New fasdtitle', now() - '21 days'::INTERVAL, '123'),
    ('worfdsads', now() - '21 days'::INTERVAL, 'adfaf'),
    ('qwadsfer', now() - '21 days'::INTERVAL, 'zxvv'),
    ('asdfalkj', now() - '21 days'::INTERVAL, 'ture'),
    ('11111', now() - '21 days'::INTERVAL, '0000'),
    ('tafdtttt', now() - '21 days'::INTERVAL, '234'),
    ('gggewrgg', now() - '21 days'::INTERVAL, '1wfut'),
    ('title one', now() - '21 days'::INTERVAL, 'ABCDES'),
    ('Nedeww title', now() - '21 days'::INTERVAL, '123'),
    ('worads', now() - '21 days'::INTERVAL, 'adfaf'),
    ('sqwer', now() - '20 days'::INTERVAL, 'zxvv'),
    ('asgdfalkj', now() - '19 days'::INTERVAL, 'ture'),
    ('111fd11', now() - '18 days'::INTERVAL, '0000'),
    ('tttvseett', now() - '17 days'::INTERVAL, '234'),
    ('ggaggg', now() - '16 days'::INTERVAL, '1wfut'),
    ('titsle one', now() - '15 days'::INTERVAL, 'ABCDES'),
    ('Nedw title', now() - '11 days'::INTERVAL, '123'),
    ('wordass', now() - '10 days'::INTERVAL, 'adfaf'),
    ('qwwer', now() - '21 days'::INTERVAL, 'zxvv'),
    ('asdffalkj', now() - '21 days'::INTERVAL, 'ture'),
    ('111k11', now() - '21 days'::INTERVAL, '0000'),
    ('stttiktt', now() - '21 days'::INTERVAL, '234'),
    ('ggjggg', now() - '21 days'::INTERVAL, '1wfut'),
    ('titiulh one', now() - '21 days'::INTERVAL, 'ABCDES'),
    ('Neiuw title', now() - '21 days'::INTERVAL, '123'),
    ('woriuds', now() - '21 days'::INTERVAL, 'adfaf'),
    ('qsdwer', now() - '21 days'::INTERVAL, 'zxvv'),
    ('asdfccxalkj', now() - '21 days'::INTERVAL, 'ture'),
    ('11vds111', now() - '21 days'::INTERVAL, '0000'),
    ('ttvsttt', now() - '21 days'::INTERVAL, '234'),
    ('ggvdsggg', now() - '21 days'::INTERVAL, '1wfut');